# Generated by Django 4.1.1 on 2022-09-28 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0005_alter_employee_hire_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='hire_date',
        ),
    ]
